import { AlertTriangle, CheckCircle2, Clock3, Hospital as HospitalIcon, MapPin } from 'lucide-react'
import type { Hospital, Referral } from '@/types/domain'
import { ReferralMap } from '@/components/map/ReferralMap'
import { CapabilityMatchMatrix } from './CapabilityMatchMatrix'

export function ReferralDetail({ referral, hospitals, admin = false }: { referral: Referral; hospitals: Hospital[]; admin?: boolean }) {
  const facility = hospitals.find((hospital) => hospital.id === referral.sentToFacilityId)
  return <section className="detail-layout"><div className="detail-main"><div className="detail-hero"><div><p className="eyebrow">REFERRAL DETAIL · {referral.id}</p><h2>{referral.patient.referenceCode}</h2><p className="muted">{referral.patient.emergencyCategory} · {referral.patient.urgencyLevel} · {referral.patient.chiefComplaint}</p></div><span className={`status-badge ${referral.status.toLowerCase()}`}><span />{referral.status.replace('_', ' ')}</span></div><div className="detail-grid"><Info label="Patient" value={`${referral.patient.age} years · ${referral.patient.sex}`} /><Info label="Created" value={new Date(referral.createdAt).toLocaleString()} /><Info label="Current facility" value={facility?.name || 'Matching facilities'} /><Info label="Updated" value={new Date(referral.updatedAt).toLocaleString()} /></div>{facility && <section className="detail-section"><h3><HospitalIcon size={16} /> Capability Match</h3><CapabilityMatchMatrix required={referral.requiredCapabilities} hospital={facility} /></section>}<section className="detail-section"><h3>Required Capabilities</h3><div className="detail-tags">{referral.requiredCapabilities.map((capability) => <span key={capability.capabilityItem}><CheckCircle2 size={14} />{capability.label}</span>)}</div></section>{facility && <section className="detail-section"><h3><HospitalIcon size={16} /> Current Facility</h3><p className="facility-detail"><strong>{facility.name}</strong><span><MapPin size={13} />{facility.address.city} · {facility.phone}</span><span className="muted">Verification: {facility.verificationStatus} · Data updated {new Date(facility.lastUpdated).toLocaleDateString()}</span></p></section>}{admin && <section className="detail-section"><h3>Escalation History</h3>{referral.escalationReason ? <div className="escalation-callout"><AlertTriangle size={16} /><span><strong>Escalation triggered</strong><small>Reason: {referral.escalationReason} · {new Date(referral.escalatedAt || referral.updatedAt).toLocaleString()}</small></span></div> : <p className="muted">No escalation recorded.</p>}</section>}<section className="detail-section"><h3><Clock3 size={16} /> Referral Timeline</h3><div className="detail-timeline">{referral.timeline.map((event) => <div key={event.id}><span /><div><strong>{event.event}</strong><small>{event.actor || 'ASTRA System'} · {new Date(event.timestamp).toLocaleString()}</small></div></div>)}</div></section></div><ReferralMap referral={referral} hospitals={hospitals} /></section>
}
function Info({ label, value }: { label: string; value: string }) { return <div className="detail-info"><small>{label}</small><strong>{value}</strong></div> }
